version: "3.4"
services:
  server-web:
    image: nginx
    ports:
      - 9000:80
    volumes:
      - ./mise_en_oeuvre_sig:/usr/share/nginx/html:ro
    restart: always

  geo-web:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./geo_visualisation:/usr/share/nginx/html:ro
    restart: always


